# Generated by Django 4.2.5 on 2023-11-20 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCGS2500k',
            fields=[
                ('tile_2500k', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'bcgs2500k',
                'managed': False,
            },
        ),
    ]
