# Generated by Django 4.2.5 on 2023-11-20 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Raw', 'Raw'), ('Adjusted', 'Adjusted'), ('Classified', 'Classified'), ('QualityControlled', 'Qualitycontrolled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')])),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'processingstatus',
                'managed': False,
            },
        ),
    ]
