# Generated by Django 4.2.5 on 2023-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UTMZone',
            fields=[
                ('zone_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utmzone',
                'managed': False,
            },
        ),
    ]
