# Valid entity names for eclipse tables
DRIVE = "drive"
EPOCH = "epoch"
LIDAR = "lidar"
NASBOX = "nasbox"
ECLIPSE = "eclipse"
BCGS20K = "bcgs20k"
UTM_ZONE = "utmzone"
DELIVERY = "delivery"
LIDAR_RAW = "lidarraw"
BCGS2500K = "bcgs2500k"
DERIVED_PRODUCT = "derivedproduct"
LIDAR_CLASSIFIED = "lidarclassified"
PROCESSING_STATUS = "processingstatus"
SPATIAL_REFERENCE = "spatialreference"
