# Generated by Django 4.2.5 on 2023-12-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LidarTile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lidartile',
            table='lidartile',
        ),
    ]
