# Generated by Django 4.2.5 on 2023-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lidar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('x_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('x_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('y_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('y_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('lidar_type', models.CharField(blank=True, max_length=1, null=True)),
                ('version', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lidar',
                'managed': False,
            },
        ),
    ]
