# Generated by Django 4.2.5 on 2023-11-20 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('derived_product_type', models.CharField(choices=[('DEM', 'Dem'), ('DSM', 'Dsm'), ('CHM', 'Chm')])),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('x_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('x_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('y_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('y_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'derivedproduct',
                'managed': False,
            },
        ),
    ]
