# Generated by Django 4.2.5 on 2023-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialReference',
            fields=[
                ('epsg_code', models.IntegerField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spatialreference',
                'managed': False,
            },
        ),
    ]
